### ISSUE TITLE
Compile fails in 2d7f66bf70d65c77ec38f64426201e3529dc2801

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#65]
> src/pool-mgr/pool_remote_box.cpp: In member function 'void horizon::PoolRemoteBox::create_pr_thread()':
src/pool-mgr/pool_remote_box.cpp:843:25: error: binding reference of type 'std::__cxx11::string& {aka std::__cxx11::basic_string<char>&}' to 'const std::__cxx11::basic_string<char>' discards qualifiers
       replace_backslash(filename);
                         ^~~~~~~~
